// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffbhsuiwzugxsualzdyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmYmhzdWl3enVneHN1YWx6ZHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjYzMjIsImV4cCI6MjA2MzUwMjMyMn0.fnBgw6zAgXXULlPnF_PLjCQnlBJoe8eahhm-E5XFKM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);